### ISSUE TITLE
Links in About don't work

### ISSUE THREAD

**Issue by MightyPork** [AresValley/Artemis#29]
archlinux, KDE Plasma.

```
kf.windowsystem: Could not find any platform plugin
kf.service.services: KApplicationTrader: mimeType "text/html" not found
kf.service.services: KApplicationTrader: mimeType "text/html" not found
kf.service.services: KApplicationTrader: mimeType "text/html" not found
```

![Screenshot_20211222_113446](https://user-images.githubusercontent.com/2041118/147079267-b3363003-cf7e-4095-95f2-1f1199adc9be.png)

what is it doing? To go to url, just exec `xdg-open <URL>`, it works reliably

ftr I tried running the `webbrowser.open()` command in REPL and it worked, I dont understand what's going wrong in artemis

```
>>> import webbrowser
>>> webbrowser.open('http://google.com')
True
>>> Opening in existing browser session.
```

**Comment by MightyPork** [comment]
it works now, idk what changed but lets close

**Comment by realMatthewBenedict** [comment]
To counter [XKCD #979](https://xkcd.com/979/), see this thread:

https://bugs.kde.org/show_bug.cgi?id=400006

The solution for me was in comment 24. Instead of selecting a program, type in manually `/usr/bin/firefox %U` into the box here:

![kdebugfix](https://github.com/AresValley/Artemis/assets/112194526/019e7d72-3dea-4b53-bcdd-41c2f4913087)
