### ISSUE TITLE
Artemis.exe must run as Admin on Windows 11

### ISSUE THREAD

**Issue by MeadeRobert** [AresValley/Artemis#31]
This level of permissions should not be required. The built exe needs to not required administrator.

**Comment by AresValley** [comment]
If the executable is compiled without forcing administrator privileges during runtime, the program may suddenly crash if the folder where it is launched is protected. If it is launched from a regular folder, you can run Artemis without any admin privileges.
The choice of forcing administrator rights at runtime was due (during and after the beta test phase) to the following points:

1) the program saves only data from the DB and reads them: these r/w operations are only possible within the folder from which it is launched (check source code). For this reason, the freedom of the program is pretty limited.
2) the source code is publicly available here and entirely viewable/editable by everyone. Everyone can analyze and compile the code they prefer and/or customize it.
3) During the launch of Artemis, we received several emails in this regard because most of the normal users tend to save the program in protected folders.

Feel free to compile your own version by removing the automatic "launch with administrator privileges" by changing the keyword uac_admin=True to uac_admin=False  in this file https://github.com/AresValley/Artemis/blob/master/spec_files/Windows/artemis.spec. Then you can normally compile the software according to the documentation.

Note: This instruction is only valid for Windows since all the UNIX-based OSs (Mac, Linux, Arm, ...) are not affected by this "issue".
