### ISSUE TITLE
Crash on Ubuntu 22.04.2 LTS - after click on play sound of station

### ISSUE THREAD

**Issue by williamdes** [AresValley/Artemis#40]
It's on a computer that is not mine.

```
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
Traceback (most recent call last):
  File "audio_player.py", line 143, in _play_audio
    mixer.init(48000, -16, 1, 1024)
pygame.error: No available audio device
Abandon (core dumped)
```

After playing one sound or sometimes after playing one by one, one will crash the app with this error.
It's a fresh Ubuntu 22.04 install.

**Comment by AresValley** [comment]
This seems to be related to the pygame library that is not able to find an audio output device to play the audio sample. Artemis 4 is rolling out these days and the 2nd RC is available here: https://github.com/AresValley/Artemis/releases. Pygame library is not present anymore due to the fact that all multimedia is manage internally by the Qt framework by the QtMultimedia library.
